### ISSUE TITLE
Enable Teachers to update grades

### ISSUE THREAD

**Issue by bmicallef1** [bmicallef1/practice-github-flow#1]
**User Story**

As a teacher I tend to lose my paper records. So, I wan't to update grades online so that the grades will be stored even if I lose the paper records.

* Persona: teacher who tends to lose paper records
* Feature: teacher updates the grades online
* Business Value: the grades will be stored even if the paper records are lost

**Task List**
- [x] make sure the date base schemes handle grades update
- [ ] create html views for updating grades
- [ ] connect the html views to the database/backend to finish the function ...

**Acceptance Criteria**
1. only for the current semester
2. works only for chrome

**Acceptance Test**
1. the teacher should be able to update existing grades for students in the course
2. the teacher should be able to remove existing grades for students in the course
3. the teacher should be able to add new grades for students in the course
